-- 01-items-seed.sql：物品目录（与 js/assets.js、js/skills.js 一致）
-- 供 inventories 触发器校验 item_id；在 01-tables.sql 之后执行（可与 02 前或后）

insert into public.items (id, type, name, price, value) values
  ('skin_default', 'skin', 'NCUTer', 0, 0),
  ('weapon_knife', 'weapon', '像素短刀', 520, 0),
  ('weapon_gloves', 'weapon', '拳击手套', 360, 0),
  ('weapon_hammer', 'weapon', '爆锤', 800, 0),
  ('weapon_claw', 'weapon', '格斗爪', 620, 0),
  ('weapon_gun', 'weapon', '训练手枪', 1200, 0),
  ('weapon_spear', 'weapon', '长柄矛', 760, 0),
  ('tool_shovel', 'tool', '工兵铲', 420, 0),
  ('tool_axe', 'tool', '战术斧', 750, 0),
  ('tool_sickle', 'tool', '月牙镰刀', 900, 0),
  ('tool_boots', 'speed', '疾行鞋', 660, 0),
  ('tool_charm', 'speed', '风行者护符', 1200, 0),
  ('survival_medkit', 'medkit', '医疗包', 0, 0),
  ('capacity_card_50', 'capacity', '背包扩容卡', 500, 0),
  ('item_rename_card', 'rename_card', '改名卡', 500, 0),
  ('gem_white', 'gem', '白宝石', 300, 300),
  ('gem_purple', 'gem', '紫宝石', 150, 150),
  ('gem_red', 'gem', '红宝石', 100, 100),
  ('gem_blue', 'gem', '蓝宝石', 80, 80),
  ('gem_yellow', 'gem', '黄宝石', 50, 50),
  ('gem_orange', 'gem', '橙宝石', 20, 20),
  ('gem_pink', 'gem', '粉宝石', 10, 10),
  ('collectible_ncut', 'collectible', 'NCUT', 0, 100),
  ('collectible_badge', 'collectible', 'NCUT校徽', 0, 100),
  ('collectible_motto', 'collectible', 'NCUT校训', 0, 100),
  ('collectible_map', 'collectible', 'NCUT地图', 0, 100),
  ('collectible_like', 'collectible', 'NCUT点赞', 0, 100),
  ('collectible_facepalm', 'collectible', 'NCUT捂脸', 0, 100),
  ('collectible_dropout', 'collectible', 'NCUT退学通知书', 0, 100),
  ('collectible_quit', 'collectible', 'NCUT不读了', 0, 100),
  ('collectible_escape', 'collectible', '逃离NCUT', 0, 100),
  ('collectible_dunpin', 'collectible', 'NCUT敦品楼', 0, 100),
  ('collectible_anniversary80', 'collectible', 'NCUT80周年logo', 0, 100)
on conflict (id) do nothing;

insert into public.items (id, type, name, price, value)
select 'skin_' || i, 'skin', 'skin_' || i, 0, 0
from generate_series(1, 52) as i
on conflict (id) do nothing;

insert into public.items (id, type, name, price, value) values
  ('skill_act_kaoqian', 'skill_active', '考前突击', 0, 0),
  ('skill_act_qiangda', 'skill_active', '课堂抢答', 0, 0),
  ('skill_act_heshui', 'skill_active', '课间补水', 0, 0),
  ('skill_act_taoke', 'skill_active', '逃课', 0, 0),
  ('skill_act_chongci', 'skill_active', '抢座冲刺', 0, 0),
  ('skill_act_fadai', 'skill_active', '上课发呆', 0, 0),
  ('skill_act_shuaye', 'skill_active', '通宵刷题', 0, 0),
  ('skill_act_bafojiao', 'skill_active', '临时抱佛脚', 0, 0),
  ('skill_act_moyu', 'skill_active', '低头摸鱼', 500, 0),
  ('skill_act_nvdaxuesheng', 'skill_active', '女大学生', 500, 0),
  ('skill_act_jiti', 'skill_active', '集体划重点', 1000, 0),
  ('skill_act_shencha', 'skill_active', '躲过审查', 1000, 0),
  ('skill_act_zhongji', 'skill_active', '终极押题', 1000, 0),
  ('skill_act_cengbiji', 'skill_active', '蹭笔记', 500, 0),
  ('skill_act_xiaoqi', 'skill_active', '课间小憩', 500, 0),
  ('skill_act_kunkun', 'skill_active', '犯困结界', 500, 0),
  ('skill_act_daike', 'skill_active', '代课', 1000, 0),
  ('skill_act_chaozuoye', 'skill_active', '抄作业', 1000, 0),
  ('skill_act_guake', 'skill_active', '挂科诅咒', 500, 0),
  ('skill_act_tushuguan', 'skill_active', '图书馆结界', 1000, 0),
  ('skill_act_gaibug', 'skill_active', '改 bug', 1000, 0),
  ('skill_act_dadianming', 'skill_active', '全体大点名', 1000, 0),
  ('skill_act_qimo', 'skill_active', '期末考试', 1000, 0),
  ('skill_psv_shuati', 'skill_passive', '刷题手感', 0, 0),
  ('skill_psv_qinxue', 'skill_passive', '勤学苦练', 0, 0),
  ('skill_psv_tice', 'skill_passive', '体测 1000 米', 0, 0),
  ('skill_psv_bingjia', 'skill_passive', '病假条', 0, 0),
  ('skill_psv_zilv', 'skill_passive', '自律学习', 0, 0),
  ('skill_psv_jiacan', 'skill_passive', '课间加餐', 0, 0),
  ('skill_psv_shuaiguo', 'skill_passive', '甩锅', 500, 0),
  ('skill_psv_bukao', 'skill_passive', '补考机会', 1000, 0),
  ('skill_psv_huashui', 'skill_passive', '划水摆烂', 500, 0),
  ('skill_psv_cuoti', 'skill_passive', '错题反噬', 500, 0),
  ('skill_psv_suitang', 'skill_passive', '随堂笔记', 1000, 0),
  ('skill_psv_xingyun', 'skill_passive', '幸运压题', 500, 0),
  ('skill_psv_kaochang', 'skill_passive', '考场运气', 1000, 0),
  ('skill_psv_raoluan', 'skill_passive', '扰乱思路', 500, 0),
  ('skill_psv_zhishi', 'skill_passive', '知识储备', 1000, 0),
  ('skill_psv_manfen', 'skill_passive', '满分气场', 1000, 0)
on conflict (id) do nothing;
